config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # mount RailsAdmin::Engine => '/exit', as: 'rails_admin'
  root to: 'welcome#index'

   
  resources :users

  get "/log-in" => "sessions#new"

  post "/log-in" => "sessions#create"

  get "/log-out" => "sessions#destroy", as: :log_out



  resources :skills do
      resources :projects
   end

   resources :projects do
    resources :subprojects
  end

  resources :posts do 
    resources :comments
  end

   get 'welcome/index'

   get 'welcome/about'

   get 'welcome/projects'

   get 'welcome/contact'

   get 'welcome/blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment< ActiveRecord::Base
    belongs_to :post

    validates :text, :presence => true
  end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    validates :name, :presence => true
  end

app/models/project.rb
class Project< ActiveRecord::Base
    belongs_to :skill

    validates :description, :presence => true
  end

app/models/skill.rb
class Skill < ActiveRecord::Base
    has_many :projects
    validates :name, :presence => true
  end

app/models/user.rb
# ActiveRecord before_save hook for this:

class User < ActiveRecord::Base
 attr_accessor :password

 validates_confirmation_of :password

 before_save :encrypt_password

 def encrypt_password
  self.password_salt = BCrypt::Engine.generate_salt

  self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

def self.authenticate(email, password)

  user = User.where(email: email).first

  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)

 user

 else

 nil

   end
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
      @comments = Comment.all
      end 

	def new
      @post = Post.find(params[:post_id])
      @comment = @post.comments.new
    end

     def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.new(comment_params)
      if @comment.save
        redirect_to post_path(@comment.post)
      else
        render :new
      end
    end

     def edit
      @post = Post.find(params[:post_id])
      @comment = Comment.find(params[:id])
    end

    def update
      @post = Post.find(params[:post_id])
      @comment = Comment.find(params[:id])
      if @comment.update(comment_params)
        flash[:notice] = "Comment updated!"
        redirect_to posts_path(@comment.post)
      else
        render :edit
      end
    end

    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      flash[:notice] = "Comment deleted"
      redirect_to posts_path
    end



  private
    def comment_params
      params.require(:comment).permit(:text)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   def index
      @posts = Post.all
      end

    def show
      @post = Post.find(params[:id])
      render :show
      end

    def new
      @post = Post.new
      render :new
      end


    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to  posts_path
      else
        render :new
       end
      end


    def edit
      @post = Post.find(params[:id])
      render :edit
      end

    def update
      @post= Post.find(params[:id])
      if @post.update(post_params)
        redirect_to posts_path
      else
        render :edit
         end
       end

    def destroy
      @post = POst.find(params[:id])
      @post.destroy
      redirect_to posts_path
       end


    private
    def post_params
      params.require(:post).permit(:name, :author, :description)
     end
   end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def new
      @skill = Skill.find(params[:skill_id])
      @project = @skill.projects.new
    end

     def create
      @skill = Skill.find(params[:skill_id])
      @project = @skill.projects.new(project_params)
      if @project.save
        redirect_to skill_path(@project.skill)
      else
        render :new
      end
    end

     def edit
      @skill = Skill.find(params[:id])
      @project = Project.find(params[:id])
    end

    def update
      @skill = Skill.find(params[:id])
      @project = Project.find(params[:id])
      if @project.update(project_params)
        flash[:notice] = "Project updated!"
        redirect_to skills_path(@project.skill)
      else
        render :edit
      end
    end

    def destroy
      @project = Project.find(params[:id])
      @project.destroy
      flash[:notice] = "Project deleted"
      redirect_to skills_path
    end



  private
    def project_params
      params.require(:project).permit(:description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create

#try to authenticate the user - if they authenticate successfully, an instance of the User model is returned

@user = User.authenticate(params[:email], params[:password])

#if an instance is returned and @user is not nil...

if @user

#let the user know they've been logged in with a flash message

flash[:notice] = "You've been logged in."

#THIS IS THE MOST IMPORTANT PART. Actually log the user in by storing their ID in the session hash with the [:user_id] key!

session[:user_id] = @user.id

#then redirect them to the homepage

redirect_to "/"

else

flash[:alert] = "There was a problem logging you in."

redirect_to log_in_path

 end
 end

 def destroy

session[:user_id] = nil

flash[:notice] = "You've been logged out successfully."

redirect_to "/"

 end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
   def index
      @skills = Skill.all
      end

    def show
      @skill = Skill.find(params[:id])
      render :show
      end

    def new
      @skill = Skill.new
      render :new
      end


    def create
      @skill = Skill.new(skill_params)
      if @skill.save
        redirect_to  skills_path
      else
        render :new
       end
      end

    def skill_params
        params.require(:skill).permit(:name, :author, :description)
       end

    def edit
      @skill = Skill.find(params[:id])
      render :edit
      end

    def update
      @skill= Skill.find(params[:id])
      if @skill.update(skill_params)
        redirect_to skills_path
      else
        render :edit
         end
       end

    def destroy
      @skill = Skill.find(params[:id])
      @skill.destroy
      redirect_to skills_path
       end

    private
    def skill_params
      params.require(:skill).permit(:name)
     end
   end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def show
	@user = user.find(params[:id])
end

def new
 @user = User.new
  end

def create

@user = User.new(user_params)

if @user.save
	UserMailer.signup_confirmation(@user).deliver
    # flash[:notice] = "Welcome to the site!"
   redirect_to "@user,notice: "signed up successfully"
else
  flash[:alert] = "There was a problem creating your account. Please try again."
  redirect_to :back

end

end

private

def user_params

params.require(:user).permit(:email, :password, :password_confirmation)

 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def projects
  end

  def resume
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
  <%= form_for [@post,@comment] do |f| %>
    <%= f.label :text %>
    <%= f.text_field :text %>
    <%= f.submit :class => "btn btn-primary" %>
  <% end %>

app/views/comments/edit.html.erb
<h1>Edit comment</h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Comments</h1>

  <ul>
    <% @comments.each do |comment| %>
      <li><%= link_to comment.text, comment_new_path(comment) %></li>
    <% end %>
  </ul>

   <hr>

  <%= link_to "New comment", new_comment_path %>
  

app/views/comments/new.html.erb
<h1>New comment for <%= @post.name %></h1>

  <%= render 'form' %>

app/views/posts/_form.html.erb
 
<div class="row">
 <%= form_for @post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :name %>
    <%= f.label :story %>
    <%= f.text_field :title %>
    <%= f.submit %> 
    <%end%>
        </div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

  <%= render "form" %>
  

app/views/posts/index.html.erb
 

 <h1>Posts</h1>

  <ul class="Listdecorations">
    <% @posts.each do |post| %>
    <div class="container panel panelcentre">
    <div class="panel panel-default">
      <div class="panel-heading"><li><%= link_to post.title, post_path(post) %></li>
      </div>
    <% end %>
  </ul>

   <hr>

  <a class="btn btn-primay"><%= link_to "New post", new_post_path %></a>
  </div>
  

app/views/posts/new.html.erb
<h1>New post</h1>

  <%= render "form" %>

app/views/posts/show.html.erb
<% if @post.comments.any? %>
    <h4>Here are the comments for this post:</h4>

    <ul>
      <% @post.comments.each do |comment| %>
        <li>
          <%= comment.text %> |
          <%= link_to "Edit", edit_post_comment_path(@post, comment) %> |
          <%= link_to "Delete", post_comment_path(@post, comment),
                                   :data => {:confirm => "Are you sure?",
                                                  :method => "delete"} %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no comments yet!</p>
  <% end %>

  <p><%= link_to "Add a comment", new_post_comment_path(@post) %></p>
  <p><%= link_to "Delete Post", post_path(@post),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></p>

  <p><%= link_to "back to posts", posts_path %></p>

app/views/projects/_form.html.erb
<%= render('layouts/errors', :object => @project) %>

  <%= form_for [@skill, @project],remote: true do |f| %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <p><%= f.submit :class => "btn btn-primary" %></p>
  <% end %>

app/views/projects/create.js.erb
$('form').remove();
$('#new_projects_link').show();
$('ul p').remove();
$('#skill_projects').append('<li><%= @project.description %> | <%= link_to "Edit",	edit_skill_project_path(@skill, @project), :class => "btn btn-default" %> | <%= link_to "Delete", skill_project_path(@skill, @project),
                         :data => {:confirm => "Are you sure?",
                         :method => "delete"},
                         :class => "btn btn-danger" %></li>')

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<%= render 'form' %>

app/views/projects/edit.js.erb
$('#edit_project_btn').hide().after('<%= j render("form") %>')

app/views/projects/new.html.erb
<h1>New project for <%= @skill.name %></h1>

  <%= render 'form' %>
  

app/views/projects/new.js.erb
$('#new_project_link').hide().after('<%= j render("form") %>')

app/views/skills/_form.html.erb
<%= render "layouts/errors", :object => @skill %>
 

 <%= form_for @skill do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name%>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.submit :class => "btn btn-primary" %>
  <% end %>
  

app/views/skills/edit.html.erb
<h1>Edit skill</h1>

  <%= render "form" %>
  
  
  

app/views/skills/index.html.erb
<h1>Skills</h1>

  <ul>
    <% @skills.each do |skill| %>
      <li><%= skill.name %></li>
      <li><%= skill.description %><li>
      <li><%= link_to skill.name, skill_path(skill) %></li>
    <% end %>
  </ul>

   <hr>

  <%= link_to "New Skill", new_skill_path %>
  

app/views/skills/new.html.erb
<h1>New skill</h1>

  <%= render "form" %>
  
  

app/views/skills/show.html.erb
  

  <% if @skill.projects.any? %>
    <h4>Here are the projects for this skill:</h4>

    <ul>
      <% @skill.projects.each do |project| %>
        <li>
          <%= project.description %> |
          <%= link_to "Edit", edit_skill_project_path(@skill, project) %> |
          <%= link_to "Delete", skill_project_path(@skill, project),
                                   :data => {:confirm => "Are you sure?",
                                                  :method => "delete"} %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no projects yet!</p>
  <% end %>

  <p><%= link_to "Add a project", new_skill_project_path(@skill) %></p>
  <p><%= link_to "Delete Skill", skill_path(@skill),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></p>

  <p><%= link_to "Return to skills", skills_path %></p>
  

app/views/users/new.html.erb
<%=form_for User.new do |f| %>

<%=f.label :email %>

<%=f.text_field :email %>

<%=f.label :password %>

<%=f.password_field :password %>

<%=f.label :password_confirmation %>

<%=f.password_field :password_confirmation %>

<%=f.submit "Sign Up" %>

<%end%>