config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # mount RailsAdmin::Engine => '/exit', as: 'rails_admin'
  root to: 'welcome#index'

   
  resources :users

  get "/log-in" => "sessions#new"

  post "/log-in" => "sessions#create"

  get "/log-out" => "sessions#destroy", as: :log_out



  resources :skills do
      resources :projects
   end

   resources :projects do
    resources :subprojects
  end

  resources :posts do 
    resources :comments
  end

   get 'welcome/index'

   get 'welcome/about'

   get 'welcome/projects'

   get 'welcome/contact'

   get 'welcome/blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment< ActiveRecord::Base
    belongs_to :post

    validates :text, :presence => true
  end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    validates :name, :presence => true
  end

app/models/project.rb
class Project< ActiveRecord::Base
    belongs_to :skill

    validates :description, :presence => true
  end

app/models/skill.rb
class Skill < ActiveRecord::Base
    has_many :projects
    validates :name, :presence => true
  end

app/models/user.rb
# ActiveRecord before_save hook for this:

class User < ActiveRecord::Base
 attr_accessor :password

 validates_confirmation_of :password

 before_save :encrypt_password

 def encrypt_password
  self.password_salt = BCrypt::Engine.generate_salt

  self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

def self.authenticate(email, password)

  user = User.where(email: email).first

  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)

 user

 else

 nil

   end
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   def index
      @posts = Post.all
      end

    def show
      @post = Post.find(params[:id])
      render :show
      end

    def new
      @post = Post.new
      render :new
      end


    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to  posts_path
      else
        render :new
       end
      end


    def edit
      @post = Post.find(params[:id])
      render :edit
      end

    def update
      @post= Post.find(params[:id])
      if @post.update(post_params)
        redirect_to posts_path
      else
        render :edit
         end
       end

    def destroy
      @post = POst.find(params[:id])
      @post.destroy
      redirect_to posts_path
       end


    private
    def post_params
      params.require(:post).permit(:name, :author, :description)
     end
   end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
   def index
      @skills = Skill.all
      end

    def show
      @skill = Skill.find(params[:id])
      render :show
      end

    def new
      @skill = Skill.new
      render :new
      end


    def create
      @skill = Skill.new(skill_params)
      if @skill.save
        redirect_to  skills_path
      else
        render :new
       end
      end

    def skill_params
        params.require(:skill).permit(:name, :author, :description)
       end

    def edit
      @skill = Skill.find(params[:id])
      render :edit
      end

    def update
      @skill= Skill.find(params[:id])
      if @skill.update(skill_params)
        redirect_to skills_path
      else
        render :edit
         end
       end

    def destroy
      @skill = Skill.find(params[:id])
      @skill.destroy
      redirect_to skills_path
       end

    private
    def skill_params
      params.require(:skill).permit(:name)
     end
   end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def show
	@user = user.find(params[:id])
end

def new
 @user = User.new
  end

def create

@user = User.new(user_params)

if @user.save
	UserMailer.signup_confirmation(@user).deliver
    # flash[:notice] = "Welcome to the site!"
   redirect_to "@user,notice: "signed up successfully"
else
  flash[:alert] = "There was a problem creating your account. Please try again."
  redirect_to :back

end

end

private

def user_params

params.require(:user).permit(:email, :password, :password_confirmation)

 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def projects
  end

  def resume
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <title>Portfolio</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '//www.google.com/jsapi','groupdate','chartkick','application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 </head>

  <body>
   <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Portfolio</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#">Link</a></li> -->
     <%= link_to "ABOUT",welcome_about_path %>
     <%= link_to "PROJECTS",welcome_projects_path %>
     <%= link_to "CONTACT",welcome_contact_path %>
     <%= link_to "BLOG",welcome_blog_path %>
      </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>